/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_me_harris_jniscratch_CreatingFileUsingJni */

#ifndef _Included_com_me_harris_jniscratch_CreatingFileUsingJni
#define _Included_com_me_harris_jniscratch_CreatingFileUsingJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_me_harris_jniscratch_CreatingFileUsingJni
 * Method:    createFileUsingJni
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_me_harris_jniscratch_CreatingFileUsingJni_createFileUsingJni
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
