/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_me_harris_jniscratch_Crypto */

#ifndef _Included_com_me_harris_jniscratch_Crypto
#define _Included_com_me_harris_jniscratch_Crypto
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_me_harris_jniscratch_Crypto
 * Method:    encrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_me_harris_jniscratch_Crypto_encrypt
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_me_harris_jniscratch_Crypto
 * Method:    decrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_me_harris_jniscratch_Crypto_decrypt
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
