/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
# include <stdio.h>
# include <stdlib.h>
# include <string.h>
#include <errno.h>

/* Header for class com_me_harris_jniscratch_CreatingFileUsingJni */

#ifndef _Included_com_me_harris_jniscratch_CreatingFileUsingJni
#define _Included_com_me_harris_jniscratch_CreatingFileUsingJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_me_harris_jniscratch_CreatingFileUsingJni
 * Method:    createFileUsingJni
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_me_harris_jniscratch_CreatingFileUsingJni_createFileUsingJni
  (JNIEnv *env , jobject obj, jstring file_path, jstring file_content){
    const char *p_file_path = (*env)->GetStringUTFChars(env, file_path, 0);
    const char *p_file_content = (*env)->GetStringUTFChars(env, file_content, 0);
    printf("the file name you want to create is %s\n",p_file_path);
    printf("the file content you want to write is %s\n",p_file_content);

    FILE* file = fopen(file_path,"w+");

    char *f_result = (char*)malloc(100 * sizeof(char));;
    if (file != NULL)
    {
        fputs(p_file_content, file);
        fflush(file);
        fclose(file);
        f_result = "successfully";
        fputs("successfully creating file", stderr);
        sprintf(f_result, " %s!","successfully creating file");
    } else {
        printf("open fail errno = %d reason = %s \n", errno, strerror(errno));
        fputs("Error creating file", stderr);
        // Allocates storage
// Prints "Hello world!" on hello_world
        strcat(f_result,"error creating file ");
        sprintf(f_result, "%d %s!", errno,strerror(errno));
    }
//    return (*env)->NewStringUTF(env, p_file_path);
    return (*env)->NewStringUTF(env, f_result);
}
#ifdef __cplusplus
}
#endif
#endif


