/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_me_harris_jniscratch_PackageValidate */

#ifndef _Included_com_me_harris_jniscratch_PackageValidate
#define _Included_com_me_harris_jniscratch_PackageValidate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_me_harris_jniscratch_PackageValidate
 * Method:    getPublicKey
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_me_harris_jniscratch_PackageValidate_getPublicKey
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
