version: '2.1'
orbs:
  android: circleci/android@2.4.0
  #   android: circleci/android@1.0.3
  # dt: datatheorem/mobile-secure-orb@1.0.0
jobs:
  assembleDebugOrRelease:
    executor:
      name: android/android-machine
      resource-class: large
      tag: default
    steps:
      - checkout
      - run:
          name: Assemble Debug build
          command: ./gradlew assembleDebug --stacktrace
      - run:
          name: show  build results
          command: ls -alSh app/build/outputs/apk/debug
      - save_cache:
          key: dt-mobile-app-cache
          paths:
            - app/build/outputs/apk/debug
      - store_artifacts:
          path: app/build/outputs/apk/debug
          destination: debugApk


workflows:
  version: 2
  build:
    jobs:
      - assembleDebugOrRelease:
          filters:
            branches:
              only:
#                - master
                - main
                - release
