name: Build Debug
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[Build]')"

    steps:
      - name: Checkout the code
        uses: actions/checkout@v5

      - name: Install `dependency` on Ubuntu
        shell: bash
        run: |
          sudo apt install build-essential tree  -y
          echo "cpu core num is "
          nproc  

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: gradle
      - name: Cache Gradle packages
        uses: ./.github/actions/cache-build-paths
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }} 
      - name: Build the app
        run: ./gradlew assembleDebug "-Dorg.gradle.jvmargs=-XX:+UseZGC -XX:+ZGenerational -Xmx8g"

      - name: show outputs
        shell: bash
        run: |
          tree app/build -L 3
